spring.application.name=ordercreationservice
server.port=8081

management.endpoints.web.exposure.include=health,prometheus
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Server mTLS
server.ssl.enabled=true
server.ssl.certificate=file:/certs/ordercreationservice.crt
server.ssl.certificate-private-key=file:/certs/ordercreationservice.key
server.ssl.client-auth=need
server.ssl.trust-certificate=file:/certs/ca.crt

# Management port zonder TLS (voor Prometheus scraping)
management.server.port=18081
management.server.ssl.enabled=false

# Client SSL bundle voor outbound mTLS
spring.ssl.bundle.pem.client.keystore.certificate=file:/certs/ordercreationservice.crt
spring.ssl.bundle.pem.client.keystore.private-key=file:/certs/ordercreationservice.key
spring.ssl.bundle.pem.client.truststore.certificate=file:/certs/ca.crt

downstream.menu.url=${MENU_URL:https://menuservice:8082}
downstream.order.url=${ORDER_URL:https://orderservice:8083}
