spring.application.name=ordercreationservice
server.port=8081

management.endpoints.web.exposure.include=health,prometheus
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true

downstream.menu.url=${MENU_URL:http://localhost:8082}
downstream.order.url=${ORDER_URL:http://localhost:8083}
