spring.application.name=orderservice
server.port=8083

management.endpoints.web.exposure.include=health,prometheus
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Server mTLS
server.ssl.enabled=true
server.ssl.certificate=file:/certs/orderservice.crt
server.ssl.certificate-private-key=file:/certs/orderservice.key
server.ssl.client-auth=need
server.ssl.trust-certificate=file:/certs/ca.crt

# Management port zonder TLS (voor Prometheus scraping)
management.server.port=18083
management.server.ssl.enabled=false
