spring.application.name=gatewayservice
server.port=8080

management.endpoints.web.exposure.include=health,prometheus
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true

spring.cloud.gateway.routes[0].id=ordercreation
spring.cloud.gateway.routes[0].uri=${ORDERCREATION_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/orders,/orders
